In [5]:
# 初始化
%load_ext autoreload
%autoreload 2
import sys
import os
import re
os.chdir("E:\\GitHub\\QA-abstract-and-reasoning")
sys.path.append("E:\\GitHub\\QA-abstract-and-reasoning")

In [6]:
# from batcher import *
from utils.saveLoader import Vocab
from utils.config import VOCAB_PAD
import tensorflow as tf
vocab = Vocab(VOCAB_PAD)

In [7]:
%run ./utils/params

In [8]:
params

{'mode': 'train',
 'decode_mode': 'greedy',
 'greedy_decode': True,
 'debug_mode': False,
 'beam_size': 3,
 'max_enc_len': 200,
 'max_dec_len': 40,
 'vocab_size': 32940,
 'batch_size': 64,
 'epochs': 8,
 'steps_per_epoch': 1295,
 'checkpoints_save_steps': 2,
 'learning_rate': 0.01,
 'adagrad_init_acc': 0.1,
 'max_grad_norm': 0.8,
 'embed_size': 300,
 'enc_units': 256,
 'dec_units': 256,
 'attn_units': 128,
 'vocab_path': 'E:\\GitHub\\QA-abstract-and-reasoning\\data\\wv\\vocab_index_pad.txt',
 'train_seg_x_dir': 'E:\\GitHub\\QA-abstract-and-reasoning\\data\\train_seg_x.csv',
 'train_seg_y_dir': 'E:\\GitHub\\QA-abstract-and-reasoning\\data\\train_seg_y.csv',
 'test_seg_x_dir': 'E:\\GitHub\\QA-abstract-and-reasoning\\data\\test_seg_x.csv',
 'test_save_dir': 'E:\\GitHub\\QA-abstract-and-reasoning\\data\\result',
 'result_save_path': 'E:\\GitHub\\QA-abstract-and-reasoning\\data\\result\\test_res.csv'}

In [9]:
from seq2seq_tf2.batcher import *

In [10]:
ds = iter(batcher(vocab, params))

In [11]:
next(ds)

{'enc_input': <tf.Tensor: id=205, shape=(64, 200), dtype=int32, numpy=
 array([[32936,  7390,  1456, ..., 32939, 32939, 32939],
        [32936,   498,  1326, ..., 32939, 32939, 32939],
        [32936,   542,  2968, ..., 32939, 32939, 32939],
        ...,
        [32936,  4035,  1201, ..., 32939, 32939, 32939],
        [32936,   373,  5233, ..., 32939, 32939, 32939],
        [32936,  1634,   748, ..., 32939, 32939, 32939]])>,
 'target': <tf.Tensor: id=206, shape=(64, 40), dtype=int32, numpy=
 array([[32936,   806,  2026, ...,   255,    13, 32938],
        [32936,     0,     3, ..., 32939, 32939, 32939],
        [32936,   325,     0, ...,     0,   290, 32938],
        ...,
        [32936,     4,  3929, ..., 32939, 32939, 32939],
        [32936,     0,    69, ..., 32939, 32939, 32939],
        [32936,     4,    29, ..., 32939, 32939, 32939]])>}

In [49]:
next(ds)["target"][0]

<tf.Tensor: id=5164, shape=(40,), dtype=int32, numpy=
array([32936,     0,     3,  2021,     0,    23,  9413,  2801, 32938,
       32939, 32939, 32939, 32939, 32939, 32939, 32939, 32939, 32939,
       32939, 32939, 32939, 32939, 32939, 32939, 32939, 32939, 32939,
       32939, 32939, 32939, 32939, 32939, 32939, 32939, 32939, 32939,
       32939, 32939, 32939, 32939])>

In [14]:
vocab.id2word[32938]

'<STOP>'