# shit

In [1]:
# 基础设置
%load_ext autoreload
%autoreload 2
import os
import sys
import time
import tensorflow as tf
sys.path.append("E:\\GitHub\\QA-abstract-and-reasoning")
os.chdir("E:\\GitHub\\QA-abstract-and-reasoning")

In [ ]:
%run seq2seq_tf2/train.py --epochs 2

1 Physical GPUs, 1 Logical GPUs
Building the model ...
Initializing from scratch.
开始训练模型..
mode: train
epochs: 2
batch_size: 64
max_enc_len: 302
max_dec_len: 37
优化器信息：
name: Adam
clipnorm: 1
learning_rate: 0.01
decay: 1e-06
beta_1: 0.9
beta_2: 0.999
epsilon: 1e-07
amsgrad: False
Epoch 1 Batch 1 Loss 3.1397
Epoch 1 Batch 2 Loss 3.1889
Epoch 1 Batch 3 Loss 3.7268
Epoch 1 Batch 4 Loss 2.5972
Epoch 1 Batch 5 Loss 2.1843
Epoch 1 Batch 6 Loss 2.4704
Epoch 1 Batch 7 Loss 2.0071
Epoch 1 Batch 8 Loss 2.4526
Epoch 1 Batch 9 Loss 2.4828
Epoch 1 Batch 10 Loss 1.8599
Epoch 1 Batch 11 Loss 1.8695
Epoch 1 Batch 12 Loss 2.0444
Epoch 1 Batch 13 Loss 2.1399
Epoch 1 Batch 14 Loss 2.1955
Epoch 1 Batch 15 Loss 1.7700
Epoch 1 Batch 16 Loss 2.3578
Epoch 1 Batch 17 Loss 1.7180
Epoch 1 Batch 18 Loss 2.0114
Epoch 1 Batch 19 Loss 1.6288
Epoch 1 Batch 20 Loss 1.5244
Epoch 1 Batch 21 Loss 1.8616
Epoch 1 Batch 22 Loss 1.8346
Epoch 1 Batch 23 Loss 1.6022
Epoch 1 Batch 24 Loss 1.5044
Epoch 1 Batch 25 Loss 1.8672
Epoc

Epoch 1 Batch 269 Loss 1.8323
Epoch 1 Batch 270 Loss 1.7659
Epoch 1 Batch 271 Loss 1.8500
Epoch 1 Batch 272 Loss 1.9036
Epoch 1 Batch 273 Loss 2.1829
Epoch 1 Batch 274 Loss 1.9251
Epoch 1 Batch 275 Loss 2.0485
Epoch 1 Batch 276 Loss 1.8061
Epoch 1 Batch 277 Loss 1.8919
Epoch 1 Batch 278 Loss 1.8570
Epoch 1 Batch 279 Loss 2.2017
Epoch 1 Batch 280 Loss 2.0003
Epoch 1 Batch 281 Loss 2.0004
Epoch 1 Batch 282 Loss 2.0420
Epoch 1 Batch 283 Loss 1.9461
Epoch 1 Batch 284 Loss 1.8749
Epoch 1 Batch 285 Loss 1.7944
Epoch 1 Batch 286 Loss 2.0232
Epoch 1 Batch 287 Loss 1.9170
Epoch 1 Batch 288 Loss 1.8783
Epoch 1 Batch 289 Loss 2.0081
Epoch 1 Batch 290 Loss 1.9733
Epoch 1 Batch 291 Loss 1.8772
Epoch 1 Batch 292 Loss 2.0338
Epoch 1 Batch 293 Loss 1.8663
Epoch 1 Batch 294 Loss 1.8422
Epoch 1 Batch 295 Loss 2.1739
Epoch 1 Batch 296 Loss 1.7846
Epoch 1 Batch 297 Loss 2.2070
Epoch 1 Batch 298 Loss 1.9933
Epoch 1 Batch 299 Loss 1.9514
Epoch 1 Batch 300 Loss 1.9728
Epoch 1 Batch 301 Loss 1.8552
Epoch 1 Ba

Epoch 1 Batch 543 Loss 2.1503
Epoch 1 Batch 544 Loss 2.1424
Epoch 1 Batch 545 Loss 1.9070
Epoch 1 Batch 546 Loss 2.1906
Epoch 1 Batch 547 Loss 1.9149
Epoch 1 Batch 548 Loss 1.9342
Epoch 1 Batch 549 Loss 2.1799
Epoch 1 Batch 550 Loss 2.1262
Epoch 1 Batch 551 Loss 2.0927
Epoch 1 Batch 552 Loss 2.1668
Epoch 1 Batch 553 Loss 2.1099
Epoch 1 Batch 554 Loss 2.2421
Epoch 1 Batch 555 Loss 2.1720
Epoch 1 Batch 556 Loss 2.0439
Epoch 1 Batch 557 Loss 2.2366
Epoch 1 Batch 558 Loss 1.9358
Epoch 1 Batch 559 Loss 1.9578
Epoch 1 Batch 560 Loss 2.1301
Epoch 1 Batch 561 Loss 2.2268
Epoch 1 Batch 562 Loss 1.9175
Epoch 1 Batch 563 Loss 1.9149
Epoch 1 Batch 564 Loss 1.8875
Epoch 1 Batch 565 Loss 2.1217
Epoch 1 Batch 566 Loss 1.9711
Epoch 1 Batch 567 Loss 1.9571
Epoch 1 Batch 568 Loss 2.1765
Epoch 1 Batch 569 Loss 1.9937
Epoch 1 Batch 570 Loss 1.8339
Epoch 1 Batch 571 Loss 2.0439
Epoch 1 Batch 572 Loss 1.9174
Epoch 1 Batch 573 Loss 2.0088
Epoch 1 Batch 574 Loss 2.1908
Epoch 1 Batch 575 Loss 1.9596
Epoch 1 Ba

Epoch 1 Batch 817 Loss 2.3179
Epoch 1 Batch 818 Loss 2.3326
Epoch 1 Batch 819 Loss 2.2388
Epoch 1 Batch 820 Loss 1.9377
Epoch 1 Batch 821 Loss 1.8587
Epoch 1 Batch 822 Loss 2.1946
Epoch 1 Batch 823 Loss 2.2307
Epoch 1 Batch 824 Loss 2.4543
Epoch 1 Batch 825 Loss 2.0139
Epoch 1 Batch 826 Loss 2.2404
Epoch 1 Batch 827 Loss 2.4659
Epoch 1 Batch 828 Loss 2.1982
Epoch 1 Batch 829 Loss 2.1694
Epoch 1 Batch 830 Loss 2.0169
Epoch 1 Batch 831 Loss 2.5029
Epoch 1 Batch 832 Loss 2.3120
Epoch 1 Batch 833 Loss 2.0362
Epoch 1 Batch 834 Loss 2.3236
Epoch 1 Batch 835 Loss 2.2389
Epoch 1 Batch 836 Loss 2.2738
Epoch 1 Batch 837 Loss 1.9994
Epoch 1 Batch 838 Loss 2.1853
Epoch 1 Batch 839 Loss 2.1131
Epoch 1 Batch 840 Loss 2.2625
Epoch 1 Batch 841 Loss 2.2058
Epoch 1 Batch 842 Loss 2.2570
Epoch 1 Batch 843 Loss 2.1348
Epoch 1 Batch 844 Loss 1.8839
Epoch 1 Batch 845 Loss 2.0052
Epoch 1 Batch 846 Loss 2.0830
Epoch 1 Batch 847 Loss 2.3335
Epoch 1 Batch 848 Loss 2.2582
Epoch 1 Batch 849 Loss 2.2369
Epoch 1 Ba

In [3]:
%run seq2seq_tf2/test.py --mode "test" --batch_size 3

1 Physical GPUs, 1 Logical GPUs
Building the model ...
Creating the vocab ...
Creating the checkpoint manager
Creating the checkpoint manager
Restored from E:\GitHub\QA-abstract-and-reasoning\data\checkpoints\seq2seq_checkpoints\ckpt-4
Model restored


100%|██████████████████████████████████████████████████████████████████████████████████| 79/79 [01:03<00:00,  1.25it/s]


#### 实验dataset

In [40]:
a = tf.constant([1,2,3,4,5,6,7,8,9,10,11,12])
ds = tf.data.Dataset.from_tensor_slices(a)
ds = ds.batch(3).shuffle(5).repeat()

In [16]:
from seq2seq_tf2.batcher import batcher
from utils.saveLoader import Vocab
from utils.config import VOCAB_PAD
vocab = Vocab(VOCAB_PAD)
# get params
%run utils/params.py

In [17]:
dataset = batcher(vocab, params)

In [18]:
enc_params, dec_params = next(iter(dataset))

In [80]:
dec_params["target"]

<tf.Tensor: id=21222, shape=(64, 37), dtype=int32, numpy=
array([[   45,  2005,    48, ..., 21873, 21873, 21873],
       [  170,    47,    54, ..., 21873, 21873, 21873],
       [    4,   105,   217, ..., 21873, 21873, 21873],
       ...,
       [    4,   105,     6, ..., 21873, 21873, 21873],
       [   39,   273, 21872, ..., 21873, 21873, 21873],
       [    4,   105,   217, ..., 21873, 21873, 21873]])>

In [75]:
dec_params["dec_input"]

<tf.Tensor: id=21219, shape=(64, 37), dtype=int32, numpy=
array([[21870,    45,  2005, ..., 21873, 21873, 21873],
       [21870,   170,    47, ..., 21873, 21873, 21873],
       [21870,     4,   105, ..., 21873, 21873, 21873],
       ...,
       [21870,     4,   105, ..., 21873, 21873, 21873],
       [21870,    39,   273, ..., 21873, 21873, 21873],
       [21870,     4,   105, ..., 21873, 21873, 21873]])>

In [74]:
enc_params["enc_input"]

<tf.Tensor: id=21215, shape=(64, 10), dtype=int32, numpy=
array([[21870,   899,  1539,   180, 21872, 21873, 21873, 21873, 21873,
        21873],
       [21870,   170,    47,   767,    17,     4,   174,   767, 21872,
        21873],
       [21870,  1417,   260,   126,  1417, 21872, 21873, 21873, 21873,
        21873],
       [21870,   103,   233,   183,   502,    93, 21872, 21873, 21873,
        21873],
       [21870,  1337,   329,   182,  1417,  1332,  4670,   692,     7,
        21872],
       [21870, 21871,     6,    62,  2390,   283,  5040,  1870,  3580,
        21872],
       [21870,   275,   118,   476,    68,    77,   279, 21872, 21873,
        21873],
       [21870,  1724,    95,   107,  1278,    12,    74,     4, 21872,
        21873],
       [21870,   456,    87,  3544,  2863,   140, 21872, 21873, 21873,
        21873],
       [21870,  1188, 10302,   267,   950,   447, 21871, 13631, 21872,
        21873],
       [21870,  1319,  9360,  3011,  3868,  1405,   447,   398, 21872,
 

In [65]:
for j,i in enumerate(ds):
    print(i[0]["enc_input"])
    if j==1:break

tf.Tensor(
[[21870  1485  1437    39 21871   804   323 21872 21873 21873]
 [21870  8059 13762  8059  1036  3270   180 21872 21873 21873]
 [21870    54  2393  1145  2164   255  4166 11664 21872 21873]
 [21870     4   153   868     2  2924  4870 21872 21873 21873]
 [21870   851   848  2897    97  2543  5804 21872 21873 21873]
 [21870  1188 10302   267   950   447 21871 13631 21872 21873]
 [21870  2296  3640  1057 17870   176   492   381 21872 21873]
 [21870 21871 20423 12982     9   353   323 21872 21873 21873]
 [21870 21871 21871 21871     4    23   278 21872 21873 21873]
 [21870   103   233   183   502    93 21872 21873 21873 21873]
 [21870  3056   437  1126   863   150  2575   953 21872 21873]
 [21870   281    73    34  2519  3412   220   180 21872 21873]
 [21870   267    87    17 15972   617    17  6589    53 21872]
 [21870  1223   608   173  1140   102  4031 21872 21873 21873]
 [21870    10   214 21871   234  1470   565  2156 21872 21873]
 [21870   153    93  1542  1283    80   636 